@startuml
'https://plantuml.com/object-diagram
header Familie Objektdiagramm 2

legend
- Geschwister über Eltern ersichtlich
- Kinder können auch Eltern sein
end legend

object Person1 {
    name = "Hans"
}
object Person2 {
    name = "Margret"$
}
object Person3 {
    name = "Hansjörg"
}
object Person4 {
    name = "Lisbet"
}
object Person5 {
    name = "Lotti"
}
object Person6 {
    name = "Hildegard"
}

Person1 "V" -- Person4
Person2 "M" -- Person4

Person1 "V" -- Person5
Person2 "M" -- Person5


Person5 "M" -- Person6
Person3 "V" -- Person6

@enduml