@startuml
'https://plantuml.com/object-diagram
header Familie Objektdiagramm 2

object Person1 {
    name = "Hans"
}
object Person2 {
    name = "Margret"
}
object Person3 {
    name = "Hansjörg"
}
object Person4 {
    name = "Lisbet"
}
object Person5 {
    name = "Lotti"
}
object Person6 {
    name = "Hildegard"
}
object Person7 {
    name = "Jutta"
}
object Person8 {
    name = "erwin"
}

Person1 "V" -- Person4
Person2 "M" -- Person4

Person1 "V" -- Person5
Person2 "M" -- Person5

Person5 "M" -- Person6
Person3 "V" -- Person6

Person3 "V" -- Person8
Person7 "M" -- Person8

note "Kind aus Seitensprung" as N1
N1 - Person8

legend
Zeigt (Halb-)Geschwister über Eltern
Zeigt Kinder die selbst Kinder haben
end legend

@enduml