@startuml
'https://plantuml.com/object-diagram
header Familie Objektdiagramm 1

object Person1 {
    name = "Hans"
    schulabschluss = "..."
}
object Person2 {
    name = "Margret"
    schulabschluss = "..."
}
object Person3 {
    name = "Peter"
    schulabschluss = "..."
}
object Person4 {
    name = "Lisbet"
    schulabschluss = "..."
}
object Ehe1 {
    start = "2021-11-11"
    ende = "2021-11-12"
}
object Ehe2 {
    start = "2021-11-12"
    ende = ""
}

Ehe2 -- Person1
Ehe2 -- Person2

Ehe1 -- Person1
Ehe1 -- Person3

Person1 "Vater" -- "Kind" Person4
Person2 "Mutter" -- "Kind" Person4

note "geschiedene Ehe weil\nende definiert" as N1
N1 - Ehe1

legend
Zeigt laufende und geschiedene Ehe sowie Kinder
end legend

@enduml